-- Run this script in the Supabase SQL Editor (https://app.supabase.com -> SQL Editor)

-- 1. Create or Update Food Items Table
CREATE TABLE IF NOT EXISTS food_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    quantity INT NOT NULL,
    unit TEXT NOT NULL,
    servings INT NOT NULL,
    expiry_time BIGINT NOT NULL,
    prepared_time BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'AVAILABLE',
    donor_name TEXT NOT NULL,
    pickup_or_delivery TEXT NOT NULL DEFAULT 'Pickup',
    location TEXT NOT NULL DEFAULT 'Unknown',
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    created_at BIGINT NOT NULL DEFAULT 0,
    image_url TEXT,
    vegetarian BOOLEAN DEFAULT TRUE,
    allergens TEXT DEFAULT 'None',
    storage_condition TEXT DEFAULT 'Room Temperature',
    packed BOOLEAN DEFAULT TRUE,
    admin_safety_approval BOOLEAN DEFAULT FALSE,
    notes TEXT DEFAULT ''
);

-- Add missing columns if the table was created earlier with fewer fields
ALTER TABLE food_items ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE food_items ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE food_items ADD COLUMN IF NOT EXISTS created_at BIGINT DEFAULT 0;
ALTER TABLE food_items ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE food_items ADD COLUMN IF NOT EXISTS vegetarian BOOLEAN DEFAULT TRUE;
ALTER TABLE food_items ADD COLUMN IF NOT EXISTS allergens TEXT DEFAULT 'None';
ALTER TABLE food_items ADD COLUMN IF NOT EXISTS storage_condition TEXT DEFAULT 'Room Temperature';
ALTER TABLE food_items ADD COLUMN IF NOT EXISTS packed BOOLEAN DEFAULT TRUE;
ALTER TABLE food_items ADD COLUMN IF NOT EXISTS admin_safety_approval BOOLEAN DEFAULT FALSE;


-- 2. Create or Update Beneficiary Queue Table
CREATE TABLE IF NOT EXISTS beneficiary_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    people_count INT NOT NULL,
    requested_quantity INT NOT NULL,
    urgency TEXT NOT NULL DEFAULT 'NORMAL',
    location TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'WAITING',
    timestamp BIGINT NOT NULL,
    urgent BOOLEAN DEFAULT FALSE,
    pickup_date BIGINT,
    pickup_time TEXT DEFAULT '',
    otp TEXT DEFAULT ''
);

-- Add missing columns if table was created earlier
ALTER TABLE beneficiary_queue ADD COLUMN IF NOT EXISTS urgent BOOLEAN DEFAULT FALSE;
ALTER TABLE beneficiary_queue ADD COLUMN IF NOT EXISTS pickup_date BIGINT;
ALTER TABLE beneficiary_queue ADD COLUMN IF NOT EXISTS pickup_time TEXT DEFAULT '';
ALTER TABLE beneficiary_queue ADD COLUMN IF NOT EXISTS otp TEXT DEFAULT '';


-- 3. Create or Update Action History Table
CREATE TABLE IF NOT EXISTS action_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type TEXT NOT NULL,
    entity_id BIGINT NOT NULL,
    timestamp BIGINT NOT NULL,
    description TEXT NOT NULL,
    can_undo BOOLEAN NOT NULL DEFAULT TRUE
);


-- 4. Disable Row Level Security (RLS) so anonymous requests from app are not blocked
ALTER TABLE food_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE beneficiary_queue DISABLE ROW LEVEL SECURITY;
ALTER TABLE action_history DISABLE ROW LEVEL SECURITY;

-- 5. Create Storage Bucket for food images (if using Storage)
INSERT INTO storage.buckets (id, name, public)
VALUES ('food_images', 'food_images', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Read/Write for food_images"
ON storage.objects FOR ALL
USING (bucket_id = 'food_images')
WITH CHECK (bucket_id = 'food_images');
